### PR TITLE
fix for WP 4.7.x

### PR DESCRIPTION
**Pull request by Ciantic**
I think this works, may need more testing. 

@socki03 and @dkristoffersson can you peeps confirm if this works? Secondly can you delete @socki03 your pull request, it is not a proper fix.

I think this is a proper fix, it implements the new hidden API introduced in WP4.7 I detailed it a little bit in: #24

### CODE REVIEW

**Comment by Ciantic** [comment]
as a sidenote @bamadesigner has forgotten to update the version number in GIT repo, it is still 1.3.4.

When she's got time, I think reviewing this pull request is highly needed, I (and many others) have a lot of sites that uses CPT-Onomies.

Thanks.

**Comment by Ciantic** [comment]
I must say there is assumption in my code: anything that uses new hidden API introduced in WP4.7 the `object_ids` arg param, must not use other args.

**Review by socki03 — CHANGES_REQUESTED** [review]
Since there is an array of confirmed $cpt_taxonomies, you should probably use that.  Otherwise, in my few spot checks, works great!

**Comment by Ciantic** [comment]
Added a comment and `$cpt_taxonomies`

**Review by socki03 — APPROVED** [review]
This change has worked well for me in 4.7 & 4.7.1.

**Comment by petersuba** [comment]
I am not an expert so apologies if this does not belong here, but at first glance it seems related.
I have applied this change but still get error notices when WP_DEBUG is on. Specifically I get these two lines:
`PHP Notice:  Trying to get property of non-object in /[basedir]/public_html/wp-includes/post.php on line 6073
PHP Notice:  Trying to get property of non-object in /[basedir]/public_html/wp-includes/post.php on line 6074`

Every time a line of code touches a post which has a linked CPT-onomy. So for example if a query includes 3 posts which have been linked to a custom post type, I get 3 of these on get_posts(). Then, I get 2 of these each time I do a get_the_excerpt() for a post that has a linked CPT-onomy.

It is potentially relevant for this fix because the above referenced lines in post.php are within the function wp_queue_posts_for_term_meta_lazyload(), and specifically as it tries to iterate an array created on the back of calling 
`get_object_term_cache('$post->ID, $taxonomy ');`

So it looks to me like there is potentially an associated mess created with regards to the cache as well, I am just not sure if this is stemming from the same root cause that this fix #25 wants to address (and so it may be a partial fix) or not. I am afraid my knowledge kinda ends there!

**Comment by socki03** [comment]
@petersuba You are right that there is an issue here, but, after looking into it some more, it seems like this is something different.  The fix referenced here was for the checkbox management system on the admin side of wordpress.  I believe you have stumbled onto a whole new issue dealing with the term cache.  I just did a quick var_dump on the cached terms, and all my CPT-onomies are showing up as an array full of  NULL variables.

I recommend moving this into its own issue.

**Review by aaronsturm — APPROVED** [review]
These changes worked for our site on WordPress 4.7.1. Thanks!

**Review by keithdream — APPROVED** [review]
This fixed the issue on our site that is using wordpress 4.7.1 as well.
Thanks!

**Comment by alfonso100** [comment]
Hi, this fixes the issue for me. Will you upgrade the wordpress.org official version with this upgrade? https://wordpress.org/plugins/cpt-onomies/ thanks!

**Comment by beingtree** [comment]
This fixed memory usage and timeout errors on my site running Wordpress 4.7.2. Thanks!

**Comment by bamadesigner** [comment]
Thanks everyone! I'm working to get this into the repo.

**Comment by Ciantic** [comment]
This is now merged. Thanks.

**Pull request closed without merging**
